export default function Head() {
  return (
    <>
      <title>sninaat</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/icons8-dental-crown-office-96.png" />
    </>
  );
}
